### PR TITLE
Update project settings

### PR DESCRIPTION
**Pull request by DivineDominion**
Migrates to Swift 5, and updates project settings for Xcode 11.6/Xcode 12.

---
This change is [Reviewable](https://reviewable.io/reviews/mrmage/daterangepicker/18)

### CODE REVIEW

**Review by MrMage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mrmage/daterangepicker/18)* status: all files reviewed, 1 unresolved discussion (waiting on @DivineDominion)

___
*[DateRangePicker.xcodeproj/xcshareddata/xcschemes/DateRangePicker.xcscheme, line 47 at r1](https://reviewable.io/reviews/mrmage/daterangepicker/18#-MDEN3yYA0WZQBXttAAB:-MDEN3yYA0WZQBXttAAC:ba0sepr) ([raw file](https://github.com/mrmage/daterangepicker/blob/9436c4fdc13e270aa1bcdf0ec0d25d876b55a546/DateRangePicker.xcodeproj/xcshareddata/xcschemes/DateRangePicker.xcscheme#L47)):*
> ```
>       selectedDebuggerIdentifier = "Xcode.DebuggerFoundation.Debugger.LLDB"
>       selectedLauncherIdentifier = "Xcode.DebuggerFoundation.Launcher.LLDB"
>       language = "zh-Hans"
> ```

Would you mind removing this?

**Review by DivineDominion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mrmage/daterangepicker/18)* status: all files reviewed, 1 unresolved discussion (waiting on @MrMage)

___
*[DateRangePicker.xcodeproj/xcshareddata/xcschemes/DateRangePicker.xcscheme, line 47 at r1](https://reviewable.io/reviews/mrmage/daterangepicker/18#-MDEN3yYA0WZQBXttAAB:-MDFUgVy9gfv_U45yctu:b-896fix) ([raw file](https://github.com/mrmage/daterangepicker/blob/9436c4fdc13e270aa1bcdf0ec0d25d876b55a546/DateRangePicker.xcodeproj/xcshareddata/xcschemes/DateRangePicker.xcscheme#L47)):*
<details><summary><i>Previously, MrMage (Daniel Alm) wrote…</i></summary><blockquote>

Would you mind removing this?
</blockquote></details>

Done.

**Review by MrMage — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/mrmage/daterangepicker/18)* status: all files reviewed, 1 unresolved discussion (waiting on @MrMage)

**Comment by DivineDominion** [comment]
(Re-requesting because I'm not certain if the missing approval was an accident.)

**Review by MrMage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mrmage/daterangepicker/18)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
