### PR TITLE
Popover as an open var

### PR DESCRIPTION
**Pull request by MattTimmons**
Added the popover as an open var. This will allow to change the behavior.. and to manually close it if need be.

### CODE REVIEW

**Comment by MrMage** [comment]
I am not a fan of reusing the same popover to display different content view controllers. Sorry for not having looked into this more before, but how about this instead?

```
open func makePopover() -> NSPopover {
    let popover = NSPopover()
    popover.behavior = .semitransient
    return popover
}

open func displayExpandedDatePicker() {
    if dateRangePickerController != nil { return }

    let popover = makePopover()
    dateRangePickerController = ExpandedDateRangePickerController(dateRange: dateRange)
    dateRangePickerController?.minDate = minDate
    dateRangePickerController?.maxDate = maxDate
    dateRangePickerController?.delegate = self
    popover.contentViewController = dateRangePickerController
    popover.delegate = self
    popover.show(relativeTo: self.bounds, of: self, preferredEdge: .minY)
    updateSegmentedControl()
}
```

Another alternative would be to make makePopover() a method on a new DateRangePickerViewDelegate, but that might be overkill.

**Comment by MattTimmons** [comment]
I get your point.. but on your code here, I can't access the popover from the class where I create / IBOutlet the PickerView. I don't see how this would allow me to change that. Am I missing something? The delegate idea may be best? Ideally, I should be able to change the popover.behavior and do a popover.close() from my main class.

**Comment by MrMage** [comment]
You would need to subclass the PickerView and override makePopover(), but I think that shouldn't be too much of a problem.

Closing the popover is a different issue - how about adding a dismissDateRangePickerController method that calls dateRangePickerController.dismiss()? Would only be available starting with 10.10, but that should be okay (unless you need to support 10.9, in which case you could store an optional popover variable). Alternatively, make dateRangePickerController public fileprivate(set) but I'm not sure whether it is a good idea to expose that one.

By the way, in which app are you using the control?

**Comment by MattTimmons** [comment]
ok, that make perfect sense then.. I will make a new pull request! This is for a private business app. Your control is perfect this this.

**Pull request closed without merging**
