### PR TITLE
Update for swift 3

### PR DESCRIPTION
**Pull request by makoni**

### CODE REVIEW

**Comment by MrMage** [comment]
Thanks! I had migrated to Swift 3 privately, but forgot to push those changes. Could you try merging your changes to the updated branch or cherry-pick them and file separate pull requests for each change?

By the way, did you test compatibility with Carthage?

Lastly, which app are you using the library in? Just curious :-)

**Comment by MrMage** [comment]
P.S.: Sorry for the wasted work :'-(

**Comment by makoni** [comment]
Yes, making framework scheme shared works fine with Carthage, I've imported it via Carthage.

I will look at changes later :)

I'm trying to use it in simple app for macOS: https://itunes.apple.com/ru/app/appmetric-statistika-dla-appmetrica/id1147094095?mt=12

**Comment by makoni** [comment]
Looks like it's better to leave your version rather solve conflicts :)

I will send new pull request with russian localization.

By the way, it looks like demo app needs some autolayout to look right

**Pull request closed without merging**
