### PR TITLE
Popover Creation Exposure

### PR DESCRIPTION
**Pull request by MattTimmons**
created an open function for the popover.

### CODE REVIEW

**Review by MrMage — CHANGES_REQUESTED** [review]
Please fix the indentation. Also, given that the original commit (adding popover as an open var) is no longer in the end result, could you please remove it, e.g. by squashing both commits into one?

**Comment by MattTimmons** [comment]
hm.. Odd, I am not seeing the indention issue and the property for the popover is gone in my latest commit to the PopoverExposure branch.

**Comment by MrMage** [comment]
If you review the changes in GitHub, you see the indentation problems. Make sure to indent with tabs rather than spaces.

And the popover property is gone _in the latest commit_, but not in the one before that. I.e. the "Added the popover..." commit is bogus, so please remove it.

**Comment by MattTimmons** [comment]
ok, I will look again. But the indent is not spaces.. not sure why you are seeing that. Who indents with spaces?

**Pull request closed without merging**
